### ISSUE TITLE
Improve tests a bit more

### ISSUE THREAD

**Issue by MickL** [johannschopplich/nitro-starter#1]
Hey, I am missing a few more things for testing. Do you have any idea to to archive them?

1. If I have `console.log()` in my Nitro app, I dont see them in the tests.
2. If I change any file in my Nitro app, the tests dont rerun (only if I change a test file)
3. How to (partially) overwrite the .env file with a .test.env?

Greetings :)

**Comment by johannschopplich** [comment]
Good ideas!

Let's continue the work in [nitro-test-utils](https://github.com/johannschopplich/nitro-test-utils), shall we? 🙂
